#                                                                        #
# Default routes configuration for the AccountManager package          #
#                                                                        #

-
  name: 'All Profile methods'
  uriPattern: 'profile(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Profile'
    '@action':     'profile'
    '@format':     'html'

-
  name: 'all other security controller actions'
  uriPattern: 'accounts(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Account'
    '@action':     'index'
    '@format':     'html'

-
  name: 'All roles actions'
  uriPattern: 'roles(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Role'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Show role'
  uriPattern: 'roles/{role}/{@action}.{@format}'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Role'
    '@action':     'index'
    '@format':     'html'
  routeParts:
    role:
      objectType:  \TYPO3\Flow\Security\Policy\Role
      uriPattern:  '{roleIdentifier}'
-
  name: 'Profile action'
  uriPattern: 'account/{account}/{@action}.{@format}'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Account'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    account:
      objectType:  \TYPO3\Flow\Security\Account
      uriPattern:  '{accountIdentifier}'