#                                                                        #
# Default routes configuration for the Security.Manager package          #
#                                                                        #
-
  name: 'all other security controller actions'
  uriPattern: 'accounts(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Account'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Account action'
  uriPattern: 'account/{account}/{@action}.{@format}'
  defaults:
    '@package':    'TYPO3.AccountManagement'
    '@controller': 'Account'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    account:
      objectType:  \TYPO3\Flow\Security\Account
      uriPattern:  '{accountIdentifier}'