#                                                                        #
# Default routes configuration for the TYPO3.UserManagement package      #
#                                                                        #
-
  name: 'Authentication'
  uriPattern: 'login(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3.UserManagement'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'all other security controller actions'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package':    'TYPO3.UserManagement'
    '@format':     'html'
  appendExceedingArguments: true
