#                                                                        #
# Default routes configuration for the Security.Manager package          #
#                                                                        #
-
  name: 'Authentication'
  uriPattern: 'login(/{@action}.{@format})'
  defaults:
    '@package':    'Security.Manager'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'all other security stuff'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package':    'Security.Manager'
    '@format':     'html'
  appendExceedingArguments: true
