#                                                                        #
# Default routes configuration for the Security.Manager package          #
#                                                                        #
-
  name: 'Authentication'
  uriPattern: 'login(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3.UserManagement'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'all other security controller actions'
  uriPattern: 'security/{@controller}/{@action}(.{@format})'
  defaults:
    '@package':    'TYPO3.UserManagement'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'Account action'
  uriPattern: 'account/{@action}/{account}.{@format}'
  defaults:
    '@package':    'TYPO3.UserManagement'
    '@controller': 'Account'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    account:
      objectType:  \TYPO3\Flow\Security\Account
      uriPattern:  '{accountIdentifier}'
  appendExceedingArguments: true