TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
Security:
  Manager:
    register: TRUE