TYPO3:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          -
            events: ['postPersist', 'postUpdate', 'postRemove']
            listener: 'TYPO3\Neos\Domain\EventListener\AccountPostEventListener'

  Neos:
    moduleConfiguration:
      widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
    modules:
      management:
        label: 'Management'
        controller: '\TYPO3\Neos\Controller\Module\ManagementController'
        description: 'Contains multiple modules related to management of content'
        icon: 'icon-briefcase'
        resource: 'TYPO3_Neos_Module_Management'
        submodules:
          workspaces:
            label: 'Workspaces'
            controller: '\TYPO3\Neos\Controller\Module\Management\WorkspacesController'
            description: 'This module contains the overview of all elements within the current workspace and it enables to continue the review and publishing workflow for them.'
            icon: 'icon-th-large'
            resource: 'TYPO3_Neos_Module_Management_Workspaces'
          accountmanagement:
            label: 'Account Management'
            description: 'This module contains the overview of all elements within the current workspace and it enables to continue the review and publishing workflow for them.'
            icon: 'icon-th-large'
            resource: 'TYPO3_Neos_Module_Management_Workspaces'
      administration:
        label: 'Administration'
        controller: '\TYPO3\Neos\Controller\Module\AdministrationController'
        description: 'Contains multiple modules related to administration'
        icon: 'icon-gears'
        resource: 'TYPO3_Neos_Module_Administration'
        submodules:
          users:
            label: 'User Management'
            controller: '\TYPO3\Neos\Controller\Module\Administration\UsersController'
            description: 'The User Management module provides you with an overview of all backend users. You can group them by their properties so you are able to monitor their permissions, filemounts, member groups etc.. This module is an indispensable tool in order to make sure the users are correctly configured.'
            icon: 'icon-group'
            actions:
              new:
                label: 'Create user'
                title: 'Create a new user'
            resource: 'TYPO3_Neos_Module_Administration_Users'
          packages:
            label: 'Package Management'
            controller: '\TYPO3\Neos\Controller\Module\Administration\PackagesController'
            description: 'The Package Management module provides you with an overview of all packages. You can activate and deactivate individual packages, import new packages and delete existing packages. It also provides you with the ability to freeze and unfreeze packages in development context.'
            icon: 'icon-archive'
            resource: 'TYPO3_Neos_Module_Administration_Packages'
          sites:
            label: 'Sites Management'
            controller: '\TYPO3\Neos\Controller\Module\Administration\SitesController'
            description: 'The Sites Management module provides you with an overview of all sites. You can edit, add and delete information about your sites, such as adding a new domain.'
            icon: 'icon-globe'
            actions:
              newSite:
                label: 'Create site'
                title: 'Create a new site'
            resource: 'TYPO3_Neos_Module_Administration_Sites'
      user:
        label: 'User'
        controller: '\TYPO3\Neos\Controller\Module\UserController'
        hideInMenu: TRUE
        resource: 'TYPO3_Neos_Module_User'
        submodules:
          usersettings:
            label: 'User Settings'
            controller: '\TYPO3\Neos\Controller\Module\User\UserSettingsController'
            description: 'This module allows you to customize your backend user profile. Here you can change your active system language, name and email address. You may also configure other general features in the system.'
            icon: 'icon-user'
            resource: 'TYPO3_Neos_Module_User_UserSettings'
